version: '3.3'

services:
  uprodit_react:
    restart: always
    container_name: uprodit_react
    image: rg.fr-par.scw.cloud/prodit/uprodit_react:${VERSION}
    networks:
      - uprodit_react
    ports:
      - "5173:80"

networks:
  uprodit_react:
    driver: bridge
