name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push to GitLab
        uses: adambirds/sync-github-to-gitlab-action@v1.1.0
        with:
          destination_repository: git@gitlab.com:YOUR_GITLAB_NAMESPACE/YOUR_GITLAB_PROJECT.git
          destination_branch_name: main  # Or your default branch
          destination_ssh_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY}}