name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Mirror Script
        run: |
          # Add the mirror script execution command here
          ./mirror.sh