name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          # Configure SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Set Git configuration
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          # Add GitLab remote
          git remote add gitlab git@gitlab.com:dimassibassem99/uprodit_challenge.git

          # Push to GitLab
          git push gitlab HEAD:main
