name: CI/CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deploy script
        run: |
          chmod +x ./ci/deploy.sh
          ./ci/deploy.sh
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
