name: CI/CD

on:
  push:
    branches:
      - master # or the name of your default branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GITLAB_SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY}}
        run:
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          echo "${{ secrets.GITLAB_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
          git remote add gitlab
          git push gitlab master
