name: Push to GitLab
on:
  push:
    branches:
      - main

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
        run: |
          git remote add gitlab https://gitlab.com/dimassibassem99/uprodit_challenge.git
          git push gitlab HEAD:main